In [1]:
import random
import cx_Oracle
import datetime 
cx_Oracle.init_oracle_client(lib_dir=r"C:\OracleDBproject\instantclient_21_7")  # 여기서 각자 라이브러리 위치 설정해줘야함
connection = cx_Oracle.connect(user='admin', password='Semorang1234', dsn='semodb_high')
# 본인이 접속할 오라클 클라우드 DB 사용자이름, 비밀번호, dsn을 넣어준다.
print(connection)

<cx_Oracle.Connection to admin@semodb_high>

In [2]:
# 전체 thing들 가져오기
cursor = connection.cursor()
cursor.execute("select T.THING_ID from THING T")
thing_rows = cursor.fetchall()
total_thing_list = [i[0] for i in thing_rows]

In [3]:

# THINGRANK 한 줄 만들기
# thing에서 thing_id를 가져와야함. 주의! user 1명은 thing 1개에 대해서 1나의 thingrank만 가진다. ranks는 1부터 순차적으로 올라감(즉, 기존에 그 유저가 몇 개 만들었는지 확인해야함)
def random_thingrank(thingrank_id,user_id):
        # THINGRANK 전부 가져와서 THING_ID만 출력
        cursor = connection.cursor()
        cursor.execute("select T.THING_ID  from USERS U ,THINGRANK TR, THING T WHERE U.USER_ID = TR.USER_ID AND T.THING_ID  = TR.THING_ID AND U.USER_ID = :TEMP_USER_ID",TEMP_USER_ID = user_id)
        user_t_rows = cursor.fetchall()
        user_thing_list = [i[0] for i in user_t_rows]


        thingrank_id = 'tr_'+str(thingrank_id)
        
        thing_id = random.choice(total_thing_list)
        while thing_id in user_thing_list:
            if len(user_thing_list) == len(total_thing_list):
                print("모든 thing에 대해 thingrank 다 만들었음. 더 이상은 못 만들어")
                break
            thing_id = random.choice(total_thing_list)
            
        ranks = len(user_t_rows)+1

        thingking_year = str(random.randint(2019,2020))
        thingking_month = str(random.randint(1,12))
        thingking_day = str(random.randint(1,28))
        thingking_date = thingking_year + '-' + thingking_month + '-' + thingking_day
        thingking_date = datetime.datetime.strptime(thingking_date, '%Y-%m-%d')

        update_year = str(random.randint(2021,2022))
        update_month = str(random.randint(1,12))
        update_day = str(random.randint(1,28))
        update_date = update_year + '-' + update_month + '-' + update_day
        update_date = datetime.datetime.strptime(update_date, '%Y-%m-%d')

        return ((thingrank_id,thing_id, user_id, ranks, thingking_date, update_date))

(26057111,
 'user_1',
 4,
 datetime.datetime(2019, 9, 20, 0, 0),
 datetime.datetime(2022, 6, 4, 0, 0))

In [4]:
cursor = connection.cursor()
cursor.execute("select U.USER_ID from USERS U")
user_rows = cursor.fetchall()
total_user_list = [i[0] for i in user_rows]

In [8]:
def auto_make_thingrank(n):
    count = 0
    while count < n:
        # user 1명 랜덤 선택
        thingrank_id = count +1
        user = random.choice(total_user_list)
        one_tr = random_thingrank(thingrank_id,user)
        #return ((thingrank_id,thing_id, user_id, ranks, thingking_date, update_date))
        print("INSERT INTO THINGRANK VALUES ('{}',{},'{}',{},'{}','{}');".format(one_tr[0],one_tr[1],one_tr[2],one_tr[3],one_tr[4].date(),one_tr[5].date()))
        # cursor.execute("INSERT INTO THINGRANK VALUES (:1,:2,:3,:4,:5,:6)", one_tr)        
        count +=1

In [9]:
auto_make_thingrank(300)

INSERT INTO THINGRANK VALUES ('tr_1',12661454,'user_20',10,'2019-11-17','2021-04-02');
INSERT INTO THINGRANK VALUES ('tr_2',16718508,'user_9',5,'2020-11-27','2021-03-26');
INSERT INTO THINGRANK VALUES ('tr_3',18390076,'user_9',5,'2020-06-02','2021-09-13');
INSERT INTO THINGRANK VALUES ('tr_4',18042774,'user_37',11,'2020-12-05','2021-04-22');
INSERT INTO THINGRANK VALUES ('tr_5',25709407,'user_40',5,'2019-10-16','2022-11-23');
INSERT INTO THINGRANK VALUES ('tr_6',17163701,'user_5',11,'2020-12-27','2022-10-03');
INSERT INTO THINGRANK VALUES ('tr_7',19914111,'user_26',7,'2019-03-05','2022-09-23');
INSERT INTO THINGRANK VALUES ('tr_8',17572409,'user_23',7,'2019-08-04','2022-12-28');
INSERT INTO THINGRANK VALUES ('tr_9',18070554,'user_38',10,'2020-04-12','2022-11-02');
INSERT INTO THINGRANK VALUES ('tr_10',19913970,'user_4',11,'2019-11-06','2022-05-26');
INSERT INTO THINGRANK VALUES ('tr_11',17063413,'user_19',4,'2019-01-13','2021-10-14');
INSERT INTO THINGRANK VALUES ('tr_12',25458448,'user_31',4,'2020-11-07','2022-03-26');
INSERT INTO THINGRANK VALUES ('tr_13',16731142,'user_9',5,'2019-05-22','2022-04-11');
INSERT INTO THINGRANK VALUES ('tr_14',18118531,'user_10',10,'2020-01-03','2021-02-13');
INSERT INTO THINGRANK VALUES ('tr_15',19913970,'user_18',3,'2019-10-12','2021-11-08');
INSERT INTO THINGRANK VALUES ('tr_16',26248029,'user_18',3,'2020-04-18','2022-04-22');
INSERT INTO THINGRANK VALUES ('tr_17',15955832,'user_12',5,'2019-02-13','2022-11-28');
INSERT INTO THINGRANK VALUES ('tr_18',18390076,'user_28',6,'2019-08-15','2022-01-18');
INSERT INTO THINGRANK VALUES ('tr_19',19994629,'test3',1,'2020-03-03','2022-03-26');
INSERT INTO THINGRANK VALUES ('tr_20',16060477,'user_9',5,'2020-09-07','2022-05-06');
INSERT INTO THINGRANK VALUES ('tr_21',19913970,'user_48',6,'2020-02-16','2022-03-14');
INSERT INTO THINGRANK VALUES ('tr_22',23317507,'user_17',6,'2019-07-02','2022-05-28');
INSERT INTO THINGRANK VALUES ('tr_23',23178356,'user_7',3,'2019-12-12','2021-10-19');
INSERT INTO THINGRANK VALUES ('tr_24',16947896,'user_26',7,'2019-09-26','2021-10-04');
INSERT INTO THINGRANK VALUES ('tr_25',16947896,'user_32',5,'2019-10-06','2022-01-16');
INSERT INTO THINGRANK VALUES ('tr_26',20546259,'user_11',8,'2019-04-28','2021-03-16');
INSERT INTO THINGRANK VALUES ('tr_27',17050121,'user_4',11,'2019-08-24','2022-06-13');
INSERT INTO THINGRANK VALUES ('tr_28',17262371,'user_32',5,'2020-02-10','2021-10-12');
INSERT INTO THINGRANK VALUES ('tr_29',18223652,'user_8',8,'2020-10-05','2022-08-02');
INSERT INTO THINGRANK VALUES ('tr_30',26248029,'test4',1,'2020-08-04','2022-07-02');
INSERT INTO THINGRANK VALUES ('tr_31',25458448,'user_45',8,'2020-05-25','2021-11-08');
INSERT INTO THINGRANK VALUES ('tr_32',26390340,'user_2',7,'2019-05-04','2021-11-07');
INSERT INTO THINGRANK VALUES ('tr_33',17470753,'user_5',11,'2020-02-27','2022-03-17');
INSERT INTO THINGRANK VALUES ('tr_34',15955832,'user_4',11,'2019-10-13','2022-05-22');
INSERT INTO THINGRANK VALUES ('tr_35',17126506,'user_10',10,'2019-10-07','2022-03-24');
INSERT INTO THINGRANK VALUES ('tr_36',18070554,'user_25',2,'2020-09-20','2022-07-14');
INSERT INTO THINGRANK VALUES ('tr_37',23382779,'test4',1,'2019-04-25','2021-01-12');
INSERT INTO THINGRANK VALUES ('tr_38',17470753,'user_3',10,'2019-05-14','2021-01-25');
INSERT INTO THINGRANK VALUES ('tr_39',18120193,'user_25',2,'2019-02-06','2022-12-14');
INSERT INTO THINGRANK VALUES ('tr_40',15955832,'user_36',6,'2020-04-04','2021-05-25');
INSERT INTO THINGRANK VALUES ('tr_41',16060477,'test3',1,'2019-03-16','2021-01-14');
INSERT INTO THINGRANK VALUES ('tr_42',23317507,'user_47',7,'2020-05-20','2022-10-05');
INSERT INTO THINGRANK VALUES ('tr_43',19913970,'user_39',12,'2020-12-02','2022-09-11');
INSERT INTO THINGRANK VALUES ('tr_44',18223652,'user_37',11,'2019-05-24','2021-03-26');
INSERT INTO THINGRANK VALUES ('tr_45',17470753,'user_3',10,'2019-04-26','2022-05-20');
INSERT INTO THINGRANK VALUES ('tr_46',23382779,'user_12',5,'2019-06-02','2022-03-24');
INSERT INTO THINGRANK VALUES ('tr_47',19994629,'user_28',6,'2020-06-03','2022-05-12');
INSERT INTO THINGRANK VALUES ('tr_48',18042774,'user_12',5,'2020-01-11','2022-05-23');
INSERT INTO THINGRANK VALUES ('tr_49',12074539,'user_31',4,'2019-05-17','2021-12-19');
INSERT INTO THINGRANK VALUES ('tr_50',26390340,'user_20',10,'2020-11-09','2021-09-23');
INSERT INTO THINGRANK VALUES ('tr_51',18120193,'user_30',6,'2019-04-18','2021-08-23');
INSERT INTO THINGRANK VALUES ('tr_52',25292488,'user_50',10,'2019-11-16','2021-05-04');
INSERT INTO THINGRANK VALUES ('tr_53',12074539,'user_25',2,'2019-04-06','2022-02-07');
INSERT INTO THINGRANK VALUES ('tr_54',18042774,'user_24',3,'2020-01-11','2021-10-04');
INSERT INTO THINGRANK VALUES ('tr_55',18118531,'user_1',13,'2019-11-12','2021-06-06');
INSERT INTO THINGRANK VALUES ('tr_56',26390340,'user_27',12,'2020-10-08','2022-09-06');
INSERT INTO THINGRANK VALUES ('tr_57',19914111,'user_10',10,'2020-10-24','2022-05-11');
INSERT INTO THINGRANK VALUES ('tr_58',16718508,'user_23',7,'2019-05-03','2021-09-09');
INSERT INTO THINGRANK VALUES ('tr_59',26070557,'user_18',3,'2019-03-19','2022-06-04');
INSERT INTO THINGRANK VALUES ('tr_60',16630137,'user_38',10,'2019-09-27','2021-09-20');
INSERT INTO THINGRANK VALUES ('tr_61',26248029,'user_3',10,'2019-03-10','2022-05-19');
INSERT INTO THINGRANK VALUES ('tr_62',26390340,'user_19',4,'2020-05-28','2022-06-28');
INSERT INTO THINGRANK VALUES ('tr_63',16630137,'user_49',6,'2019-12-26','2022-01-16');
INSERT INTO THINGRANK VALUES ('tr_64',16947896,'user_36',6,'2019-07-15','2021-12-11');
INSERT INTO THINGRANK VALUES ('tr_65',17720028,'user_8',8,'2019-04-01','2021-05-04');
INSERT INTO THINGRANK VALUES ('tr_66',16947896,'user_13',7,'2020-03-28','2021-07-17');
INSERT INTO THINGRANK VALUES ('tr_67',25290079,'user_33',7,'2020-03-17','2021-08-03');
INSERT INTO THINGRANK VALUES ('tr_68',17050121,'user_27',12,'2019-02-23','2021-10-22');
INSERT INTO THINGRANK VALUES ('tr_69',16718508,'user_12',5,'2020-03-09','2021-10-05');
INSERT INTO THINGRANK VALUES ('tr_70',18390076,'user_27',12,'2019-09-26','2022-04-15');
INSERT INTO THINGRANK VALUES ('tr_71',12518380,'user_36',6,'2020-12-10','2021-04-19');
INSERT INTO THINGRANK VALUES ('tr_72',15955832,'user_1',13,'2019-08-05','2021-08-01');
INSERT INTO THINGRANK VALUES ('tr_73',16642883,'user_8',8,'2019-12-20','2022-09-07');
INSERT INTO THINGRANK VALUES ('tr_74',17163701,'user_21',6,'2019-11-15','2021-02-27');
INSERT INTO THINGRANK VALUES ('tr_75',20546259,'user_7',3,'2019-10-13','2021-07-16');
INSERT INTO THINGRANK VALUES ('tr_76',26070557,'user_45',8,'2020-11-18','2022-08-04');
INSERT INTO THINGRANK VALUES ('tr_77',16731142,'user_26',7,'2019-04-04','2022-11-26');
INSERT INTO THINGRANK VALUES ('tr_78',17720028,'user_37',11,'2020-12-27','2021-11-15');
INSERT INTO THINGRANK VALUES ('tr_79',16947896,'user_48',6,'2019-11-05','2022-02-24');
INSERT INTO THINGRANK VALUES ('tr_80',18223652,'user_27',12,'2019-08-02','2021-08-13');
INSERT INTO THINGRANK VALUES ('tr_81',18070554,'user_25',2,'2020-05-28','2022-08-06');
INSERT INTO THINGRANK VALUES ('tr_82',16731142,'user_50',10,'2020-04-09','2022-01-11');
INSERT INTO THINGRANK VALUES ('tr_83',17852141,'user_17',6,'2019-11-07','2021-08-23');
INSERT INTO THINGRANK VALUES ('tr_84',17856847,'test2',1,'2020-06-17','2021-09-14');
INSERT INTO THINGRANK VALUES ('tr_85',23317507,'user_16',4,'2020-10-25','2022-06-15');
INSERT INTO THINGRANK VALUES ('tr_86',18013943,'user_44',7,'2019-05-02','2022-11-12');
INSERT INTO THINGRANK VALUES ('tr_87',19994629,'user_26',7,'2019-12-18','2022-05-15');
INSERT INTO THINGRANK VALUES ('tr_88',16726942,'user_24',3,'2020-06-17','2022-01-07');
INSERT INTO THINGRANK VALUES ('tr_89',18095238,'user_8',8,'2020-11-18','2021-11-23');
INSERT INTO THINGRANK VALUES ('tr_90',17063413,'user_6',6,'2020-10-01','2022-05-11');
INSERT INTO THINGRANK VALUES ('tr_91',17163701,'user_13',7,'2019-07-01','2022-09-04');
INSERT INTO THINGRANK VALUES ('tr_92',25592608,'user_3',10,'2020-01-19','2021-03-03');
INSERT INTO THINGRANK VALUES ('tr_93',18390076,'user_36',6,'2019-01-20','2021-11-04');
INSERT INTO THINGRANK VALUES ('tr_94',18223652,'user_49',6,'2020-06-10','2022-06-13');
INSERT INTO THINGRANK VALUES ('tr_95',18013943,'user_20',10,'2020-11-08','2021-03-28');
INSERT INTO THINGRANK VALUES ('tr_96',16630137,'user_20',10,'2020-11-17','2022-10-18');
INSERT INTO THINGRANK VALUES ('tr_97',26431599,'user_33',7,'2020-10-23','2022-01-24');
INSERT INTO THINGRANK VALUES ('tr_98',17063413,'user_16',4,'2020-03-05','2021-12-24');
INSERT INTO THINGRANK VALUES ('tr_99',18070554,'user_49',6,'2020-05-19','2022-06-13');
INSERT INTO THINGRANK VALUES ('tr_100',23382779,'user_27',12,'2019-07-25','2022-06-05');
INSERT INTO THINGRANK VALUES ('tr_101',18390076,'user_14',5,'2020-04-17','2021-09-19');
INSERT INTO THINGRANK VALUES ('tr_102',16642883,'user_7',3,'2019-05-19','2021-05-14');
INSERT INTO THINGRANK VALUES ('tr_103',17126506,'user_28',6,'2020-10-11','2021-08-22');
INSERT INTO THINGRANK VALUES ('tr_104',12661454,'abc123',1,'2019-12-21','2021-01-12');
INSERT INTO THINGRANK VALUES ('tr_105',17572409,'user_7',3,'2020-06-14','2022-02-14');
INSERT INTO THINGRANK VALUES ('tr_106',25290079,'user_5',11,'2020-10-25','2022-12-06');
INSERT INTO THINGRANK VALUES ('tr_107',18118531,'user_34',7,'2020-05-15','2021-05-14');
INSERT INTO THINGRANK VALUES ('tr_108',16642883,'user_49',6,'2020-08-24','2022-08-11');
INSERT INTO THINGRANK VALUES ('tr_109',23178356,'user_36',6,'2019-11-26','2022-11-28');
INSERT INTO THINGRANK VALUES ('tr_110',26390340,'user_14',5,'2019-06-28','2021-07-10');
INSERT INTO THINGRANK VALUES ('tr_111',19994629,'user_36',6,'2020-10-19','2021-11-07');
INSERT INTO THINGRANK VALUES ('tr_112',25709407,'user_49',6,'2020-09-18','2022-11-18');
INSERT INTO THINGRANK VALUES ('tr_113',25290079,'user_47',7,'2019-02-15','2022-12-05');
INSERT INTO THINGRANK VALUES ('tr_114',12661454,'user_14',5,'2020-12-04','2021-09-23');
INSERT INTO THINGRANK VALUES ('tr_115',23266088,'user_42',7,'2020-02-20','2021-07-13');
INSERT INTO THINGRANK VALUES ('tr_116',25290079,'user_33',7,'2019-12-13','2022-07-16');
INSERT INTO THINGRANK VALUES ('tr_117',25592608,'user_39',12,'2020-11-15','2021-02-09');
INSERT INTO THINGRANK VALUES ('tr_118',18095238,'user_26',7,'2020-08-03','2022-01-09');
INSERT INTO THINGRANK VALUES ('tr_119',25290079,'user_4',11,'2019-09-25','2021-10-24');
INSERT INTO THINGRANK VALUES ('tr_120',16679243,'user_38',10,'2019-05-10','2021-10-15');
INSERT INTO THINGRANK VALUES ('tr_121',18120193,'user_15',8,'2020-11-01','2022-01-19');
INSERT INTO THINGRANK VALUES ('tr_122',26070557,'user_20',10,'2020-09-17','2022-05-22');
INSERT INTO THINGRANK VALUES ('tr_123',25592608,'user_32',5,'2019-10-27','2022-11-13');
INSERT INTO THINGRANK VALUES ('tr_124',20546259,'user_4',11,'2019-02-05','2021-02-05');
INSERT INTO THINGRANK VALUES ('tr_125',23266088,'test2',1,'2020-12-25','2022-10-05');
INSERT INTO THINGRANK VALUES ('tr_126',17163701,'user_9',5,'2019-03-03','2022-05-20');
INSERT INTO THINGRANK VALUES ('tr_127',19913970,'user_24',3,'2019-08-09','2022-08-14');
INSERT INTO THINGRANK VALUES ('tr_128',16642883,'user_26',7,'2020-06-21','2021-03-22');
INSERT INTO THINGRANK VALUES ('tr_129',16060477,'user_26',7,'2020-09-10','2022-08-24');
INSERT INTO THINGRANK VALUES ('tr_130',17050121,'user_48',6,'2020-03-11','2021-02-25');
INSERT INTO THINGRANK VALUES ('tr_131',17126506,'user_8',8,'2019-11-22','2022-07-04');
INSERT INTO THINGRANK VALUES ('tr_132',25755835,'user_21',6,'2019-11-28','2021-04-14');
INSERT INTO THINGRANK VALUES ('tr_133',17126506,'user_1',13,'2020-01-09','2021-06-02');
INSERT INTO THINGRANK VALUES ('tr_134',18118531,'user_17',6,'2020-10-28','2022-12-07');
INSERT INTO THINGRANK VALUES ('tr_135',17050121,'user_28',6,'2020-07-12','2021-09-14');
INSERT INTO THINGRANK VALUES ('tr_136',17856847,'user_9',5,'2020-10-22','2022-12-04');
INSERT INTO THINGRANK VALUES ('tr_137',16947896,'user_4',11,'2020-09-28','2022-01-19');
INSERT INTO THINGRANK VALUES ('tr_138',16718508,'user_12',5,'2020-05-20','2021-06-24');
INSERT INTO THINGRANK VALUES ('tr_139',16947896,'user_44',7,'2019-05-17','2021-05-13');
INSERT INTO THINGRANK VALUES ('tr_140',12518380,'user_20',10,'2019-08-15','2022-01-03');
INSERT INTO THINGRANK VALUES ('tr_141',25755835,'user_36',6,'2020-10-25','2022-02-02');
INSERT INTO THINGRANK VALUES ('tr_142',19914111,'user_16',4,'2020-10-07','2021-02-06');
INSERT INTO THINGRANK VALUES ('tr_143',16726942,'user_18',3,'2019-06-01','2022-09-21');
INSERT INTO THINGRANK VALUES ('tr_144',16947896,'user_3',10,'2020-06-13','2021-12-18');
INSERT INTO THINGRANK VALUES ('tr_145',17063413,'user_19',4,'2019-02-23','2022-04-14');
INSERT INTO THINGRANK VALUES ('tr_146',17050121,'user_30',6,'2019-01-18','2022-03-19');
INSERT INTO THINGRANK VALUES ('tr_147',26390340,'test5',1,'2019-07-21','2022-02-19');
INSERT INTO THINGRANK VALUES ('tr_148',16726942,'user_39',12,'2019-06-17','2021-11-27');
INSERT INTO THINGRANK VALUES ('tr_149',19914111,'user_11',8,'2020-01-07','2022-01-09');
INSERT INTO THINGRANK VALUES ('tr_150',17050121,'user_21',6,'2019-02-01','2021-11-20');
INSERT INTO THINGRANK VALUES ('tr_151',23382779,'user_45',8,'2020-04-15','2021-01-07');
INSERT INTO THINGRANK VALUES ('tr_152',17572409,'user_28',6,'2020-12-12','2022-01-07');
INSERT INTO THINGRANK VALUES ('tr_153',25592608,'user_19',4,'2020-12-25','2021-08-02');
INSERT INTO THINGRANK VALUES ('tr_154',26070557,'user_29',7,'2020-06-22','2021-07-19');
INSERT INTO THINGRANK VALUES ('tr_155',20546259,'user_19',4,'2019-10-08','2021-12-18');
INSERT INTO THINGRANK VALUES ('tr_156',17126506,'user_12',5,'2019-01-15','2021-11-15');
INSERT INTO THINGRANK VALUES ('tr_157',15955832,'user_7',3,'2020-12-11','2021-04-25');
INSERT INTO THINGRANK VALUES ('tr_158',16947896,'user_30',6,'2019-05-10','2022-12-27');
INSERT INTO THINGRANK VALUES ('tr_159',17063413,'test3',1,'2020-07-03','2021-06-28');
INSERT INTO THINGRANK VALUES ('tr_160',16642883,'user_10',10,'2020-06-18','2021-11-06');
INSERT INTO THINGRANK VALUES ('tr_161',16726942,'user_1',13,'2019-08-23','2022-01-27');
INSERT INTO THINGRANK VALUES ('tr_162',12518380,'user_18',3,'2019-08-21','2021-06-16');
INSERT INTO THINGRANK VALUES ('tr_163',17856847,'user_32',5,'2020-08-20','2022-09-05');
INSERT INTO THINGRANK VALUES ('tr_164',23178356,'user_24',3,'2020-01-17','2022-07-04');
INSERT INTO THINGRANK VALUES ('tr_165',19994629,'test3',1,'2020-07-16','2021-03-04');
INSERT INTO THINGRANK VALUES ('tr_166',26070557,'user_39',12,'2020-05-12','2022-10-06');
INSERT INTO THINGRANK VALUES ('tr_167',17852141,'user_14',5,'2019-02-14','2022-07-18');
INSERT INTO THINGRANK VALUES ('tr_168',25458448,'user_5',11,'2020-07-10','2021-02-21');
INSERT INTO THINGRANK VALUES ('tr_169',17063413,'user_22',7,'2019-04-08','2022-03-25');
INSERT INTO THINGRANK VALUES ('tr_170',18095238,'user_42',7,'2019-04-26','2022-11-15');
INSERT INTO THINGRANK VALUES ('tr_171',18390076,'user_10',10,'2019-11-22','2021-05-04');
INSERT INTO THINGRANK VALUES ('tr_172',18070554,'test',1,'2020-07-04','2021-05-16');
INSERT INTO THINGRANK VALUES ('tr_173',18118531,'user_47',7,'2019-11-24','2021-09-26');
INSERT INTO THINGRANK VALUES ('tr_174',16679243,'user_16',4,'2020-11-14','2022-10-25');
INSERT INTO THINGRANK VALUES ('tr_175',18095238,'user_45',8,'2019-09-14','2022-06-22');
INSERT INTO THINGRANK VALUES ('tr_176',18223652,'user_38',10,'2020-11-11','2021-02-11');
INSERT INTO THINGRANK VALUES ('tr_177',12518380,'user_4',11,'2020-08-22','2021-02-20');
INSERT INTO THINGRANK VALUES ('tr_178',19994629,'user_20',10,'2020-07-20','2022-08-16');
INSERT INTO THINGRANK VALUES ('tr_179',25290079,'user_39',12,'2020-11-08','2021-05-14');
INSERT INTO THINGRANK VALUES ('tr_180',17852141,'user_48',6,'2020-01-22','2021-04-24');
INSERT INTO THINGRANK VALUES ('tr_181',17126506,'user_24',3,'2020-08-27','2022-06-23');
INSERT INTO THINGRANK VALUES ('tr_182',19913970,'user_35',8,'2020-07-22','2022-04-06');
INSERT INTO THINGRANK VALUES ('tr_183',17126506,'user_26',7,'2020-01-01','2021-10-23');
INSERT INTO THINGRANK VALUES ('tr_184',18095238,'user_17',6,'2020-06-22','2021-05-13');
INSERT INTO THINGRANK VALUES ('tr_185',26070557,'user_50',10,'2019-02-26','2022-07-03');
INSERT INTO THINGRANK VALUES ('tr_186',26070557,'user_36',6,'2020-05-10','2021-06-19');
INSERT INTO THINGRANK VALUES ('tr_187',12074539,'user_32',5,'2020-09-09','2021-03-09');
INSERT INTO THINGRANK VALUES ('tr_188',15955832,'user_3',10,'2020-06-12','2022-12-24');
INSERT INTO THINGRANK VALUES ('tr_189',16060477,'user_19',4,'2020-09-03','2021-05-25');
INSERT INTO THINGRANK VALUES ('tr_190',26431599,'user_12',5,'2019-06-19','2021-09-04');
INSERT INTO THINGRANK VALUES ('tr_191',18095238,'test3',1,'2020-05-17','2021-07-06');
INSERT INTO THINGRANK VALUES ('tr_192',16060477,'user_12',5,'2020-04-04','2021-01-27');
INSERT INTO THINGRANK VALUES ('tr_193',16410914,'user_19',4,'2019-03-24','2021-04-21');
INSERT INTO THINGRANK VALUES ('tr_194',25592608,'user_17',6,'2019-06-06','2021-02-23');
INSERT INTO THINGRANK VALUES ('tr_195',17470753,'user_41',8,'2020-07-21','2021-06-08');
INSERT INTO THINGRANK VALUES ('tr_196',12661454,'user_2',7,'2019-10-16','2022-02-03');
INSERT INTO THINGRANK VALUES ('tr_197',18070554,'user_42',7,'2019-03-07','2022-12-14');
INSERT INTO THINGRANK VALUES ('tr_198',16679243,'test4',1,'2020-02-05','2021-06-26');
INSERT INTO THINGRANK VALUES ('tr_199',26390340,'user_20',10,'2019-08-19','2022-07-26');
INSERT INTO THINGRANK VALUES ('tr_200',16731142,'user_18',3,'2020-11-02','2021-04-16');
INSERT INTO THINGRANK VALUES ('tr_201',23317507,'user_27',12,'2020-01-21','2021-12-10');
INSERT INTO THINGRANK VALUES ('tr_202',25592608,'user_15',8,'2019-07-28','2021-06-21');
INSERT INTO THINGRANK VALUES ('tr_203',16947896,'test',1,'2020-01-07','2022-01-20');
INSERT INTO THINGRANK VALUES ('tr_204',12518380,'user_14',5,'2020-01-06','2021-07-06');
INSERT INTO THINGRANK VALUES ('tr_205',17050121,'user_20',10,'2020-10-12','2022-07-08');
INSERT INTO THINGRANK VALUES ('tr_206',19914111,'test',1,'2020-07-24','2022-09-14');
INSERT INTO THINGRANK VALUES ('tr_207',15955832,'user_22',7,'2020-10-17','2022-01-25');
INSERT INTO THINGRANK VALUES ('tr_208',18042774,'user_29',7,'2019-04-05','2021-11-01');
INSERT INTO THINGRANK VALUES ('tr_209',25755835,'user_28',6,'2020-02-04','2021-01-01');
INSERT INTO THINGRANK VALUES ('tr_210',16679243,'user_2',7,'2019-09-01','2021-04-23');
INSERT INTO THINGRANK VALUES ('tr_211',15955832,'user_16',4,'2019-12-03','2022-04-05');
INSERT INTO THINGRANK VALUES ('tr_212',18223652,'user_32',5,'2020-10-21','2022-10-21');
INSERT INTO THINGRANK VALUES ('tr_213',20546259,'user_32',5,'2019-06-23','2021-08-10');
INSERT INTO THINGRANK VALUES ('tr_214',16679243,'test5',1,'2020-06-15','2022-12-18');
INSERT INTO THINGRANK VALUES ('tr_215',16060477,'user_25',2,'2020-02-02','2021-10-03');
INSERT INTO THINGRANK VALUES ('tr_216',20546259,'user_45',8,'2020-10-25','2021-02-20');
INSERT INTO THINGRANK VALUES ('tr_217',18070554,'user_29',7,'2020-07-28','2021-07-23');
INSERT INTO THINGRANK VALUES ('tr_218',23178356,'user_32',5,'2019-06-20','2022-11-21');
INSERT INTO THINGRANK VALUES ('tr_219',16679243,'user_36',6,'2020-06-26','2021-08-27');
INSERT INTO THINGRANK VALUES ('tr_220',16731142,'user_17',6,'2020-10-02','2021-06-21');
INSERT INTO THINGRANK VALUES ('tr_221',17126506,'user_2',7,'2019-11-26','2021-09-21');
INSERT INTO THINGRANK VALUES ('tr_222',18042774,'user_24',3,'2019-12-03','2022-10-15');
INSERT INTO THINGRANK VALUES ('tr_223',26390340,'user_34',7,'2019-06-05','2021-12-18');
INSERT INTO THINGRANK VALUES ('tr_224',12074539,'user_5',11,'2020-07-04','2021-03-06');
INSERT INTO THINGRANK VALUES ('tr_225',18095238,'user_2',7,'2020-05-06','2022-09-16');
INSERT INTO THINGRANK VALUES ('tr_226',17572409,'user_18',3,'2020-05-16','2021-12-26');
INSERT INTO THINGRANK VALUES ('tr_227',17163701,'user_36',6,'2020-03-11','2022-05-21');
INSERT INTO THINGRANK VALUES ('tr_228',18013943,'user_8',8,'2019-06-14','2021-02-17');

In [18]:
connection.commit()